= Devoxx France 2025
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:resourcesdir: ./resources
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 2
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]


== Mercredi
=== 09h00 - 09h45 (Amphi BLEU) KEYNOTE - Et si l'intelligence artificielle n'existais pas
.Speakers: Luc Julia

==== Notes

cest quoi l'IA 1956 modelisation d'un neuronne a dortmund
1958 ca marche pas. l'hiver de l'IA
1960 nouveau idée, system expert basé sur logique et non statistic.
1990 devien fort et bat casparove au echec. ca veux devenir que c'est intelligeant ? lol

l'IA statistic reviens. machine learning
car grace a l'internet on a beaucoup de donnée.

Quand on dit l'IA ca n'existe pas, cest celle de hollywood.
AI general generique n'existe pas.

un IA est un outil, comme une scie un marteau.
un IA dans un domaine particulier il est meilleur que moi, sinon il sert a rien. comme un marteau.

IA generative existe depuis 2018.
c'est une evolution et non revolution.
Machine learning avec les donnée d'internet 1995 reussi a reconnaitre des chat à 98%. Un enfant reconnais à 100% apres avoir vu 2 chat.

Deep learning avec capacité de calcule et donnée plus elevé.
On a passé a des million de donnée, on utilise des GPU, on pete la planette.

IA generative c'est +++. des milliard ou trillion de donnée. 1200 milliard de parametres (c'est l'internet en entier). Pour créer un model qui va pomper tout ca ca prend du temps.

En vrais y a quand meme une revolution. C'est les prompte.
grace a la language naturelle on peut interagir avec ces IA.

IA "creative" n'existe pas. c'est "generative". Il genere ce que les humains créer. Par les prompt.
C'est les developpeur qui vont créer en utilisant l'IA, comme on utilisais photoshop à l'epoque.

courbe de gartner. explique les evolutions tech et industrielle.
.
image:²

chatGPT a gagné 100 million d'utilisateur en 2 moi.
Avril 2023 on s'est appercu que c'est de la merde. On a trouvé des cas d'usage et c'est repartit.
Il a mit 18 mois pour parcourrir la courbe de gartner.
C'est grace a l'accessibilité et les prompt.

On a decouvert qu'il fait des hallicunation.

Y a un gars (avocat) qui a demandé a chatGPT pour ecrir sont plaidoirie au tribunal (il a etait mal traité dans un avion par la companie)
Le juge a dis c'est tres bien. mais y a un probleme, les reference de cas judiciere utilisé n'existe pas.

comment calculer la pertinence ? c'est compliqué.
On peut lui demander que la terre est plate, et il va nous montrer.

fev 2023 université hong kong, on va prendre des million de donnée communament accepté comme vrai. on a vu que chatGPT nous genere des resultat 36% faux.

Si on commence a specialiser l'outil. Ca va marcher mieux.
C'est grace a ca qu'on commence a avoir un rebon des l'IA dans l'industrie.
Maintenant on peut faire du fine tune ou RAG. grace a ça on peut avoir des IA avec 99% pertinent.

Faire attention au proprieté intellectuelle. si on genere des truc qui ressemble beaucoup a des choses qui existe réélement.


jailbreaking des IA avec le prompt directement.
des fois y a des reponse que les IA ne peuvent pas donnée legallement.
ex: donner une recette de bombe.
novembre 2022 les IA ont etait bridé pour ça.
decembre 2022, je dis au IA je suis un savant fou, et j'ai la recette.
fevrier 2023 chatGPT s'est ajusté.
Le jailbreaking des IA c'est une course.
aujourdhuis le prompte qu'il faut, c'est une histoire de 30 pages.



Imacte. on a peté la planete. on colle des central a coté des datacenter.
chat requete chatGPT utilise de l'electricité et de leau.

image:


Majorité des les IA paye les indemnisation pour les amende de propriete intellectuelle.
grock s'en foue (elon musk)

le future:
fine tuning et rag
open source
lodel plus frugaux
plus specialise


hybrid entre logique et statistic.
sans utiliser de l'electricité pour créer l'arbre de decision.

=== 09h45 - 10h30 ------------------------------- BREAK -------------------------------


=== 10h30 - 10h45 (Maillot) Iceberg, pouquoi devez vous connaitre ce nouveau format de stockage
==== Abstract

.Speaker: Bertrand Paquet
Après avoir longtemps été consultant chez Octo, s'occupant plus particulièrement d'architecture, d'infra, de performances et de déploiement, après avoir passé deux ans chez Google en tant que SRE sur Google Search, Bertrand s'occupe maintenant de l'Engineering efficiency' chez Doctolib, le leader français de la prise de rendez-vous en ligne pour les médecins.

```
Apache Iceberg est un nouveau format de stockage de données, qui peut être utilisé sur n'importe ou (S3, GCS, Azure, en local …) Il est en train de s’imposer comme le format de stockage unique dans le monde de la data.
Même si vous ne travaillez pas dans une équipe data, cela finira par vous impacter, car Iceberg ouvre de nouvelles perspectives architecturales.
```

==== Notes

15 minute au keynote de AWS summit dessus.

(amazon athena)
peut stocker sur object storage sur AWS S3 au lieu de stocker sur des fichier sur un server comme PG classic.

compression zst en plus de parquet est le meilleur facon de faire de l'analytics sur Amazon athena.

dans parquet le count(*) est instentané car le nombre de ligne est dans le header des fichier. zero data scan.

on peut faire des update sur les données !
faux gerer les expired/orphan files. En general service providers vous aides.


SRI vs Data


=== 11h15 - 11h35 ------------------------------------- BREAK -------------------------------------


=== 11h35 - 12h20 (Amphi Bleu) Github copilot, aller plus loin que completion de code
==== Abstract
.Speaker: Kim-Adeline Miguel
Je suis Senior Software Engineer chez GitHub, où je travaille sur et avec GitHub Copilot. Avant ça, je travaillais sur l'extension open-source Python pour VS Code depuis Vancouver, et avant avant ça j'étais en ESN. Au quotidien je suis plutôt axée TypeScript et IA, mais aussi tricot 🧶, Final Fantasy 14 🎮 et plantes vertes 🪴
```
La Programmation Orienté Données est une approche alternative à la Programmation Objet, qui vous permet d'organiser votre code différemment. Elle s'appuie sur les records, les types scellés, les switch expressions exhaustives, et le pattern matching. Ce lab part d'une application simple, et vous guide pas à pas vers la réorganisation du code en appliquant les principes de la programmation orientée données. Il vous permettra d'avoir une meilleure vision de ce qu'est la programmation orientée données, et de pouvoir l'appliquer à bon escient dans vos applications.
```

.Speaker: Sandra Parlant
```
Solutions architect who has worked with different customers in pre-sales, architecture, cloud, DevOps, development, and consulting. I am passionate about designing and delivering custom solutions for customers. When I'm not at work, I enjoy spending time with my baby girl and my family.
```

==== Notes

je oeut ajouter des instruction pour copilote dans le fichier .github
copilot-instructions.md

je oeux ajouter des personnal instructions (ex: use french)
ça persist sur github globallement pour moi.

je peux retry les question et meme instruction personalisé avec un autre model.

je peux swith entre les reponses des different model et revenir.

il existe un mode "edit" au lieu de "ask" dans github sur les IDE.
Il faut ajouter la codebase en context.
We can add features by asking via prompt. and it will generate code for us.
il me propose de revoir avant d'accpter les changement. fichier par fichier.

on peut generer une description de la PR sur github.

github advance security peut revoir les PR en terme de securité.
Copilot autofix permet de avoir des solution de fix.

agent mode fonctionne avec MCP protocole
il peut agire sur github directement créé des issue, PR ect.
on a aussi plus d'interaction et suivis des etapes.





=== 12h20 - 13h30 ------------------------------------- LUNCH -------------------------------------


=== 12:35 - 12:50 (Paris 141 ) Snippets - non rien a avoir avec du code
==== Abstract
.speaker Ane DIEZ DE TUESTA
Ane est Software Engineer chez Datadog. Elle est aussi oratrice de conférences et facilitatrice graphique.

```
Connaissez-vous les "Snippets"?
Je vous présente l'utilisation de "snippets" comme un journal personnel de travail.
Également connus comme "Google Snippets", ils prétendent être le secret de productivité de la Silicon Valley.```
```

==== Notes



=== 12h50 - 13h30 ------------------------------------- LUNCH -------------------------------------

=== 13h30 - 14h15 (Amphi Bleu) vol au dessus d'un nid de vulnerabilité
==== Abstract
.speaker Damien Lucas
Ayant commencé ma carrière dans le mainframe, je suis maintenant développeur et Tech Lead Java depuis plusieurs années. J'adore lire la doc avant de me lancer dans le code. Et par dessus tout, j'aime échanger et transmettre sur ce que j'ai pu apprendre de mes expériences, des discussions avec mes pairs, des conférences vues ...
```
Durant ce talk, je vous présenterai les deux formats de SBOM existants : CycloneDX, soutenu par l'OWASP, et SPDX, par la Linux Foundation. Je vous expliquerai également comment nous avons automatisé leur génération depuis notre CI, ainsi que leur exploitation via DependencyTrack.
```

==== Notes
les BOMs
mend renovate c'est comme dependabot

faut un outils qui scan les composant en prod:
existant: IDE plugins, sonar, jfrog xray.
Mais on a pas la vision des composant en prod
Encore mieux: des alertes automatique.

2020 solarwinds est piraté, infiltré dans leur reseau. ingecté du malware dans la pipeline et la prochaine livraison.
tout les client sont impacté par leur mise a jour.
perte de 40 million de dolard.
les USA impose de fournir un BOM pour tout provider de software.

les normes de BOM
SPDX(linux) vs cycloneDX(owasp)

SPDX orienté licence
Norme ISO
example petclinic de spring
format json
.image:
tout est un package

CycloneDX
orienté bill of material
norme ECMA (moin rigide qu'ISO)
tout est component
format XML et protobof

conversion enter les 2 model est possible

plusieur facon de generer un SBOM
outils externe ? vs integré à l'appli
Syft peut pousser avec un github action le SBOM.
github peut aussi generer le SBOM dans insights => dependency graph
docker scout est un scanner aussi pour les images docker.
Scan de dependence appli et scan congainer (image de base ect, tout pour le runtime) est complementaire.

ya des outils qui ne prend pas en compte le tree shaking fait au build donc n'extrait pas du SBOM ce qui n'est pas utilisé dans le package final.


comment exploiter
Dependency track ou docker scout
Dependency track donne un score de prediction d'exploitation dans la nature.
On peut setup des alerte selon des critere custom.
ex: licence GPL utilisé dans l'entreprise.

pour Cyclone DX on a des variants pour autres sujet que le code et runtime concernant les appli.
xBOM ou le Fullstack BOM
SaaS BOM va parler des services externe utilisé (ex: kafka)
Cryptography BOM va resencer tout les asset lié au crypto (algorithm, clé, certif, certificats, java bouncy castle ect..)
CBOM ou cdxgen permet de le faire
HBOM hardware
Formulation (CI, ect)
MLBOM (les donnée utilisé pour l'entrainer)

y a cyber resilience act qui commence a imposer des SBOM partout.



=== 14h15 - 14h35 ------------------------------------- BREAK -------------------------------------

=== 14h35 - 15h20 (Amphi Bleu) OAUTH2 et OpenID sous le capot
==== Abstract
.speaker Daniel Garnier-Moiroux
Daniel est ingénieur dans les équipes Spring, où il contribue à Spring Security, et sur solutions dans le domaine de la gestion d'identité et du Single-Sign On. Il enseigne également l'ingénierie informatique aux Mines de Paris. Dans sa carrière, il a également été tech lead et consultant.
```
OpenID et OAuth2 sont les protocoles d'authentication et d'authorization web les plus répandus. Ce sont des protocoles compliqués, difficile à appréhender pour les novices, avec plein de concepts qui se mélangent. Souvent expliqué, rarement compris, ils se basent pourtant sur quelques primitives simples à mettre en oeuvre
```

==== Notes
OUAUTH2 framework d'authorization (permission)
via des access token
c'est un ensemble de spec dont RFC6749 qui est l'initial.

ex: je donne access a mon-albul-photo.com à acceder a mes photo sur google photos. sans partager mon mdp google.

OpenID Connect (OIDC) est un framework d'authentification
identité detenu par un provider d'identité
donc faire du SSO
basé sur Oauth2 avec des tokens

BAD IDEA
image:

OAUTH2
image:

token d'identification ne doit pas transiter par nos PC.
REAL OAUTH2
image:


intellij run anything "presentation"


1. rediriger l'utilisateur pour qu'il cherche un code chez google

    y a une relation pre etablis entre my-photos-blabal.com et google, pour que il puisse rediriger vers google pour que je puisse me loger et donner un code à myphotoblabla.
    C'est la ou il definit chez google le ouauth2/callback url.

    google a un api pour ce genre de connu api
    google.api/.wellknown/openid
    on trouve le url d'authentfication
    "authorization-endpoint": accounts.googel/o/oauth2/v2/auth

2. utiliser le code de google pour un token d'identité

    implementer le url callback endpoint sur notre app.
    sur .well-known/openid prendre le "token_endpoint" :ouath2.googleapis.com/token
    appeler ce url avec les parametres comme le type de code et grant_type
    et fournir le code avec le http header "authentication".
    On optien un JWT.

    on peut decrypter du JWT (base64) sur JWT.io ou un outil en cli "step + jq"

3. je vais metre ça dans la session de mon user sur mon appli my-photos-blabla


Faire du single page ap avec OAUTH2 et OICD est different.
En general on a un backend pour pas avoir les key exposé au client.
ou alors un gateway devant le signle page app qui gere l'authententification.

Oauth2 browser base apps. (recommend un BFF)

=== 15h20 - 15h40 ------------------------------------- BREAK -----------------------------------

=== 15h40 - 16h25 (Amphi Bleu) Kubernetes en 2025
==== Abstract
.speaker Alain Regnier
Alain Regnier est Architecte Technique et Entrepreneur passionné d’innovation.
Il est CTO de la société Kubo Labs, spécialiste de Kubernetes on premise et sur le Cloud.

```
Au cours de cette présentation nous ferons le tour des dernières évolutions à connaitre pour mieux utiliser Kubernetes en 2025!
Au programme: Gateway, kubectl debug, CRD, Operator, partage de GPU, Image Volumes, modification dynamique de ConfigMap, Container Storage Interface et SnapShots, eBPF, CEL pour le contrôle d'admission, request/limits au niveau des Pods, Kueue pour gérer les jobs, sécurité...
```

==== Notes

CRD permet d'ajouter de nouveau type d'objet dans K8s
Operator permet d'etendre les fonctionalité de K8s. permet de automatiser le cycle de vie d'une application
Operator = controller + CRD

kubecl debug (vs exec shell) d'un pod qui n'a pas de bash sur l'image de base.
ajoute un sidecar dans le pod.

kubectl d'un node
le root FS est visible sous /host.

arakid est un genre de busybox avec diff outils dedans que je peux utiliser comme sidecar dans le pod pour "kubectl debug".

Gateway api (vs old ingress)
routage inter namespace
support Grpc
canary deployment blue/green
c'est fournis comme un CRD (n'est pas inclus dans les version K8s)
ingress nginX va etre archivé.

CSI (container storage interface)
Volume Snapshot d'un persistentVolume.
sont egallement des CRD.

PVC persistent volume claim


eBPF
ça permeet d'ajouter des fonctionalité au kernel.
beaucoup utilisé pour du monitoring.


CEL common expression language.
jamais utiliser de "latest" dans les deploiment K8s
ValidationAdmission policy permet de controller ce que les dev envoie au Kube API. les CEL sont tres utils ici.


ConfigMap Dynamic Update
ça marche quand les config sont monté en volume. pas en env vars.


Image Volumes
permet de monter directement le contenue d'une image OCI dans le FGS ou plusieur container  d'un pod
decoupler l'appli de ses fichier de config.


Request/Limit
on va les avoir au global au niveau du pod.
on peut tjr affiner au niveau container


Kueue (vs jobs et cronjobs)
solution cloud native.

Template (vs kustomize)

Secrets store CSI Driver


=== 16h25 - 17h00 ------------------------------- NETWORKING -------------------------------


=== 17h00 - 17h30 (Maillot) ça marche dans mon devcontainer !
==== Abstract
.speaker Benoit Moussaud

Avec plus de 20 ans d'expérience en informatique d'entreprise, du développement à l'architecture globale d'applications d'entreprise complexes, mon domaine de prédilection est l'automatisation sous toutes ses formes: coté Dev en étant impliqué dans le projet open source Ant, l'intégration et le déploiement continue (CI /CD), les pratique DevOps appliquées non seulement aux application legacy mais aussi les applications cloud natives modernes. Les outils ne sont pas une fin: le processus humain est aussi essentiel : Agilité, Continuous Delivery et DevOps sont des méthodes et des pratiques. Intervenant dans de nombreuses conférences européennes (France, Suisse, Espagne, Belgique et Italie).
.speaker Josephine St-Joannis

```
Configurer son environnement de développement peut être soit un plaisir (au début), soit une corvée (si cela se répète trop souvent).
Il est généralement nécessaire de passer par un fichier README.md ou une page Wiki, de suivre les instructions (dans le bon ordre) en copiant-collant des commandes plus ou moins correctes et à jour (installation d'outils, synchronisation de référentiels) pour pouvoir lancer un build qui se termine par un succès et enfin l'application. Quel effort ! Surtout s'il faut recommencer avec le projet d'à côté en espérant qu'il n'y ait pas de conflit.
Le projet devcontainer (https://containers.dev) offre une solution à ce problème : il permet de définir l'environnement de développement as code et de l'instancier automatiquement.
Dans cette présentation axée sur la démonstration, nous verrons quels sont les prérequis, les différents concepts clés et comment plonger facilement dans le monde merveilleux des containers de développement.
```

==== Notes

image:

un env complet de dev dans un container.
dabord on specifie tout les parametre du runtime dont j'ai besoin pour dev.
Evite que les dev ait besoin d'installer des truc pour modifier/evoluer leur envs de dev.
Aussi eviter de pourrir sa machine pour des tache temporaire.

Colima ?

Je peux partager tout mon FS avec le container, mais
je peux aussi isoler les source en clonnant le repo dans le container.
il va créer un volume pour la persistence des volume (les vol des container sont moin analysé par les antivirus, donc le code plus rapide a compiler)

vegeta permet de faire du microbenchmark

si on manque de resource en local, on peu projeter avec devcontainers sur github codespace.


pas de private endoint sur codespace pour le moment.



=== 17h30 - 17h50 ------------------------------------- BREAK -------------------------------------

=== 17h50 - 18h20 (Amphi Bleu) Be more productive with IDEA
==== Abstract
.speaker Marit van Dijk

Marit van Dijk is a software developer with over 20 years of diverse experience across various roles and companies. As a Java Champion and Developer Advocate at JetBrains, she is passionate about building awesome software in collaboration with amazing people, and making developers’ lives better.

```
IntelliJ IDEA is designed to help developers stay in the flow while working. It has a powerful editor, refactorings, navigation, and all kinds of smart features to help you write and read code. At the same time, it is jam packed with tools professional developers need, like Maven, Gradle, Spring, Git, Databases, Test tools and more. And did I mention a fantastic debugger?
In this talk, you will see how IntelliJ IDEA supports your workflow without having to leave the IDE, and learn how you can be a happier and more productive developer.
```

==== Notes

Nullness is implicit in java.
Rendre ceci explicit avec JSpecify.
on peut deja faire cela avec Kotlin.
semantic: Nulleness types
@Nullable
@NonNull
@Unknown

Optional a un runtime overhead.
Pas possible de changer la JDK et spring APIs pour metre Optional partout.

Pourquoi JSpecify vs Jakarta nullable

Set the default to non-null to reduce noise.

@NullMarked veux dire qu'au niveau du package, quand j'ai pas d'annotation, c'est du nonNull.

unsafe code should break the build.
Nullaway permet de fail si on a des alert JSpecify.
on utilise gradle errorprone plugin. Nullaway est une extension.

nullability of arrays and varargs is supported.
Generic types as well.

grace a JSpecify on peut faire des library java qui peuvent etre utilisé en Kotlin

assert state permet de defnir des contrat sur les body des reponse de restClient.

JSpecify is a zero cost abstraction of nulleness.
Value classes + jspecify qui enleve un bit par objet, on aura de l'optim important au niveau java.

Optionnel est tjr important pour les valeur de retour et gestion fonctionnel style.
Mais le nullable avec zero cost peut nous preparer pour le nullness de java avec valhala

== Jeudi

=== 09h00 - 09h25 (Amphi BLEU) Language IA et propagande
==== Abstract
.Speakers Elodie Mielczareck
Elodie Mielczareck est sémiolinguiste (sémiologue pour le grand public). Elle est spécialisée dans le langage verbal (sémantique) et le langage non verbal (body language). Elle conseille également les dirigeants d’entreprise et accompagne certaines agences de communication et relations publiques internationales, notamment sur la question de la Raison d’être.

```
Les mots façonnent notre réel : ils construisent, manipulent, imposent, en un mot, ils performent ! Jamais neutre, toujours engagé, le langage devient un algorithme, calibré, biaisé, orienté. On parle souvent des politiciens et des communicants, mais les vrais maîtres du langage ne sont-ils pas devenus les codeurs et ingénieurs de notre époque? Comment les mots peuvent-ils encore avoir un sens à l’heure de Netflix et ChatGPT ? Voici les quelques questions qui seront soulevées lors de ce Keynote
```


=== 09h35 - 10h00 (Amphi BLEU) La territorialization des infrastructure comme levier de pouvoir
==== Abstract
.Speaker: Ophélie Coelho
Ophélie Coelho est une chercheuse indépendante, autrice et conférencière, spécialisée dans la géopolitique du numérique. Elle est doctorante associée au Centre Internet et Société du CNRS et du laboratoire Carism (Panthéon-Assas).
En 2023, elle publie "Géopolitique du numérique : l'impérialisme à pas de géants" aux Éditions de l'Atelier, où elle analyse la redistribution des pouvoirs entre acteurs étatiques et privés, ainsi que l'influence croissante des multinationales technologiques dans les relations internationales.


```
Alors que des investissements massifs sont annoncés pour le développement de l'IA, que représentent les infrastructures de données comme levier de pouvoir géopolitique ? Nous verrons dans cette keynote comment les acteurs de la tech et leurs Etats d'origine mettent en place des mécanismes de dépendances, qu'ils peuvent ensuite instrumentaliser pour orienter les relations internationales et les normes
```

==== Notes
.


=== 10h00 - 10h30 ------------------------------------- BREAK -------------------------------------


=== 10h30 - 11h15 (Amphi Bleu) Les cles de l'architecture pour les devs
==== Abstract
.Speaker: CYRILLE MARTRAIRE
Cyrille est CTO co-fondateur d'Arolla, un cabinet de conseil qui rassemble 130 enthousiastes de l'ingénierie logicielle moderne (Software Craft). Il est le fondateur de la communauté Paris Software Crafters, qui compte aujourd'hui plus de 5000 membres, est l'auteur du livre : "Living Documentation" chez Addison-Wesley et co-auteur du livre "Software Craft" chez Dunod. Cyrille est orateur régulier dans des conférences en Europe et au-delà.


```
Si vous êtes dev, vous participez de plus en plus aux décisions d’architecture, et c’est mieux ainsi. Mais quel est le minimum à savoir parmi toute l’étendue du sujet ?

Cette session vous donnera les principales clés pour améliorer votre quotidien dans vos projets, chaque clé étant illustrée par des exemples concrets en code, json ou diagramme.

Nous verrons notamment comment faire évoluer des API ou des flux asynchrones sans faire souffrir vos collègues, comment découper vos modules, vos données et vos instances pour moderniser ou scaler, comment faire des bons compromis techniques, et jusqu'à quel point se marier à nos frameworks favoris. Nous verrons aussi comment rester pragmatique tout en profitant des innovations. Vous repartirez avec une vision plus claire des différentes dimensions de l'architecture logicielle.
```

==== Notes
premiere clé c'est de savoir vivre dans l'insertitude.
Tout change tjr avec les system modulaire.
on peut pas tout savoir et tout prevoir.

context diagram C4
image:

2eme clé est "commencer à parler du problem" (sans parler de solution).
un probleme bien posé c'est pas que les comportement attendu, mais les quality attributes aussi (volume, availability, language/techno ...ect)

3eme clé talk negotiate educate people.

Technical constraints guide the design.
DDD says business logic should drive the design.
But quality attributes are related to business requirements.
image:


4eme clé est la modularité. Subdomains.
modular monolith (pragmatic solution)

Tout solution apport des nouveau probleme.

5eme clé architectural perspective
domaines(business logic) vs module(code)
complexité de chaque partit de l'architecture dois correspondre au competence des personne qui gere ces partit de l'archi.

image:

Modular monolit has top 2 layers divided, but runtime unified.

6eme clé, guarde des option reversible pas cher.

7eme clé, reconnaitre des problem difficile, et les deleguer (cloud, middleware, service managé ...ect)

La fin du modular monolith :( on passe en microservices.
nouvelle solution: nouveau problemes

ArchUnit.
Des ADR dans le code.




=== 11h15 - 11h35 ------------------------------------- BREAK -------------------------------------

=== 11h35 - 12h20 (Amphi Bleu) Kuberenetes comment flinguer sa prod
==== Abstract
.Speaker: Denis Germain
Je suis Staff Platform Engineer chez Lucca (ex-Deezer, Lectra, E.Leclerc), spécialiste de Kubernetes depuis 2017. J'ai accompagné les entreprises où j'ai travaillé dans la migration de workloads legacy vers des plateformes conteneurisées, tout en aidant les équipes de développement à adopter ce nouveau paradigme.

```
N'en déplaise à ceux qui pensent que Kubernetes ne sert à rien, 10 ans après le premier commit, cet outil est devenu un standard de-facto dans la gestion d'environnements containérisés en production.

Il permet à de nombreuses équipes tech de gérer de manière efficace des logiciels hétérogènes, tout en apportant aux développeurs l'autonomie qu'ils souhaitent sur l'infrastructure.

Pourtant, on ne peut pas non plus dire qu'installer, et pire... administrer un cluster Kubernetes soit quelque chose de trivial. En 7 ans de prod, dans 4 entreprises différentes, j'ai forcément rencontré de petits pépins, certains amusants (enfin... a posteriori).

Je vous raconterai tout ça, sans tabou 😉.
```

==== Notes

1)
Liveness/Readiness
deux url distinct.
Solution: Liveness ne doit pas avoir de dependence externes.

2)
l'api version n'est pas le meme que la version des binaires.
probleme d'historique ?
Solution: gitops

3)
2 virtualService/ingress pointe sur le meme url
C'est permis par la spec de ingress, mais le comportement va dependre du controller utilisé.
solution: ValidatingWebHooks avec Kyverno ou OPA GateKeeper

4)
Certificate Authority qui expire ?
Dans K8s tout les flux sont encrypté
image:
solution: monitoring

5)
systemd bug when update
solution: ne pas mettre a jour les server/nodes , destroy and create new, test new OS image before using in PROD.
approche "cattle" vs pets





=== 12h20 - 13h30 ------------------------------------- LUNCH -------------------------------------

=== 12h35 - 12h50 (Maillot) Du designe a la production, event driven architecture
==== Abstract
.Speaker: Vincent Dubois
Je suis Staff Engineer chez Primary depuis 18 mois. Avant cela j’ai passé plus de 22 ans en ESN, chez des éditeurs de logiciels ou encore en startup. Je suis développeur, mais ce qui me motive avant tout, c’est le partage et l’animation de communautés techniques.
```
Les Event-Driven Architectures nous sont souvent présentées comme des solutions parfaites pour découpler les différentes parties d’un système.
Si elles sont assez simples à mettre en oeuvre, elles viennent tout de même avec leur lot de contraintes, notamment pour suivre ce qui se passe en production.
Chez Primary, nous avons fait le choix d’une Event-Driven Architecture depuis le premier jour pour notre backend.
Je vous raconterai les hauts, les bas de ces deux dernières années, ainsi que les défis à venir. Vous repartirez avec des éléments concrets pour savoir si cela est pertinent de vous lancer dans ce style d’architecture.
```

==== Notes

Dead letter queue est une bonne pratique pour recuperer les event qui n'ont pas pu etait geré par les consumer/subscriber/handler.

Des erreur ? on rejoue. Donc il faut de l'idempotence.
Mais on rejoue pas systematiquement. ça depende et il faut une strategie definit.



=== 13h00 - 13h15 (Maillot) TDD et IA
==== Abstract
.Speaker: Benoit Prioux
Après 12 ans chez Lectra, éditeur de logiciel basé à Bordeaux, je suis maintenant Senior Software Engineer chez [Alan](https://alan.com/) depuis 4 ans.

```
Ces dernières années, l'intelligence artificielle a révolutionné notre manière d'aborder le développement logiciel.
Vous avez peut-être déjà entendu dire : "Super, avec Copilot, plus besoin d'écrire des tests, il peut les générer pour moi."
Mais est-ce vraiment compatible avec le Test Driven Development (TDD) ? 🤔

Dans cette conférence, nous explorerons comment l'IA peut être intégrée efficacement dans votre boucle de développement (🔴 - 🟢 - 🔄).
À travers des exemples concrets, nous verrons comment utiliser des outils basés sur l'IA pour améliorer et accélérer le processus de développement, tout en respectant les principes fondamentaux du TDD. 🚀
Que vous soyez sceptique ou curieux, venez découvrir comment l'IA peut devenir votre meilleur allié. 🤝
```

==== Notes

=== 13h15 - 14h35 ------------------------------------- LUNCH -------------------------------------


=== 14h35 - 15h20 (Amphi bleu) Optimiser le démarrage avec project Leyden
==== Abstract
.Speaker: Sébastien Deleuze
Sébastien travaille chez Broadcom en tant que core committer Spring Framework. Il a introduit le support de Kotlin dans les projets Spring, et travaille à intégrer différentes technologies avec le but d'optimiser l'efficacité des applications Spring en production (GraalVM, Project CRaC, CDS, Project Leyden). Il est également fan de WebAssembly depuis 2016, Kotlin Google Developer Expert et un ancien membre de l’équipe qui organise la conférence MiXiT.
```
Spring Boot 3 a introduit des optimisations visant à améliorer l’efficacité et les performances des applications Spring Boot déployées en tant que conteneurs en production.

Dans cette présentation, Sébastien migrera une application Spring Boot 2 utilisant Java 8 vers Spring Boot 3 utilisant Java 24 de façon à tirer partie de technologies telles que Virtual Threads, Spring AOT, CDS/AOT cache et Buildpacks. Sébastien partagera des benchmarks (temps de démarrage, consommation mémoire, requêtes par seconde et latence), parlera des critères les plus importants pour choisir entre GraalVM, Project CRaC et CDS/AOT cache. Il donnera également un aperçu des améliorations à venir dans Project Leyden afin d’avoir des performances maximales dès le démarrage de la JVM.
```

==== Notes

CDS class data sharing
    => AOT cache (java 24 et LTS en 25)
        => AOT cache with profiling and code complilation (Future experimental)

atteindre le warmup de la JVM plus rapidement grace a ce cache.
Training run avant de packager et livrer.

CDS ne donne pas de gain si on utilise pas les jar auto extract de spring.
image:

en demarrant l'appli avec les lib extrait et cds cahce créé, l'appli demarre plus vite etmoin de memoru footprint

 definir le dialect JDCB est une bonne pratique, ca evite que l'appli tappe a la DB au demarrage.

container avec CDS va etre plus gros ! mais c'est le tradeof a faire.

on peut créé l'image docker avec spring boot uildpack, ou alors on peux integrer le chache CDS dans notre custom dockerfile nous meme.

java 24 avec project leyden bring AOT (pas du native GraalVM, mais pour la JVM classic) AOT cache est le successor de CDS.


AOT cache (JVM)  X  Spring AOT (graalVM)
JEP 483

on peut créé le fichier aot.conf sans arrete la JVM en prod.

Crac serialize tout la memoire dans un fichier. donc les MDP !!





=== 15h20 - 15h40 ------------------------------------- BREAK -------------------------------------

=== 15h40 - 16h25 (Amphi Bleu) Requete SQL jusqu'a 1000 fois plus rapide
==== Abstract
.Speaker: Alain LESAGE
Nos données sont ce qu'il y'a de plus précieux et c'est ce pourquoi ce champ de l'informatique me passionne.

```
Les systèmes de gestion de bases de données relationnels ne sont pas magiques et ont d'abord pour but d'assurer que vos données sont bien rangées et protégées en cas de force majeur. Ceci représente un défi lorsqu'on souhaite récupérer de l'information au cœur de son SGBD, en un temps minimal. Dans cette conférence, je propose d'étudier, avec PostgreSQL, les mécanismes mis en œuvre par le moteur et à disposition de l'administrateur pour s'assurer des performances optimales. Voici les thèmes abordés :
MVCC
impact de l'architecture matérielle sur les performances
les paramètres PostgreSQL à connaître
Quoi quand, comment et pourquoi indexer (focus sur index b-tree, BRIN)
le rôle vital des statistiques pour les performances (planification et optimisation de requêtes par le moteur)
Le partitionnement est-il utile ?
Les limites de PostgreSQL aujourd'hui.
Ceci est la synthèse de mon expérience de DBA au support de milliers d'instances pour nos clients, je souhaite partager un maximum d'informations utiles aux développeurs, intégrateurs et toute personne ayant affaire à une base de données (PostgreSQL)
```

==== Notes
.
Postgresql est modulaire et extensible.
Libre et opensource
née à l'université.
Pas de rique qu'il y a du vendor locking

performence mono thread est imoortant car on fait forcement des operation de tri (qui se fait tjr en un seul thread a un moment)

index only scan permet d'avoir la valeur directement dans la table d'index sans a aller chercher les donnée dans le disk.

les orm retourne tout les colonne, et on paye ça au niveau reseau.


=== 16h25 - 17h00 ------------------------------------- BREAK -------------------------------------

=== 17h00 - 17h30 (Maillot) Nullaway
==== Abstract
.Speaker: Alexandre Navarro
Geek dans l'âme, je suis Développeur / Architecte / Tech Lead pragmatique depuis plus de 20 ans sur des applications java haute performance pour les Traders et Sales.
```
Vous aussi vous, vous êtes arrachés les cheveux sur des NullPointerException (NPE pour les intimes) en production et vous voudriez éviter cela?
Cette présentation est faite pour vous.
L'idée du talk est de vous présenter différentes techniques afin d'éviter au maximum les potentielles NPE.
Dans un premier temps, nous parlerons de l'utilisation de certaines classes, de patterns et de bonnes pratiques pour les éviter.
Le cœur de la présentation s'attardera ensuite sur la présentation et le retour d'expérience sur nullaway, un annotation processor qui permet de vérifier les potentielles NPE à la compilation.
Nous conclurons avec les avantages de nullaway mais aussi ses limites dans des projets déjà en production et nous finirons avec ce que nous réserve le jdk concernant la gestion des null dans le futur.
```

==== Notes

Jilt (staged builder) vs lombok builder (le premier permet d'avoir des objet fully initialized)

Jakarta validation ou Object.requireNonNull
Rust est safe en threading et type comparé à C°°, mais les meme perf
pas de null, pas d'exception. Option/result un objet emoty.

image:{docfile}/

Nullaway
on est obligé de noter tout les parametre de method, retour de method, attribut de class.

Jilt permet d'obliger les dev a remplir tout les champs avant de builder avec le builder.

Nullaway a certain class de jdk ou spring en dure, pour faire comme si cetait annoté avec JSpecify, meme si ce n'est pas le cas.





=== 17h30 - 17h50 ------------------------------------- BREAK -----------------------------------

=== 17h50 - 18h20 (Paris 141) Infiscal - le meilleur ami des devs pour garder les secret
==== Abstract
.Speaker: Julien Briault
Ingénieur Réseau / SRE chez Deezer la journée, et manager d’infrastructure bénévole aux Restos du Cœur le soir, je suis un peu le Batman de l’IT : un clavier pour le travail, un autre pour les Restos.

```
La gestion des secrets est un enjeu crucial pour la sécurité des infrastructures modernes. Si HashiCorp Vault a longtemps régné en maître, de nouvelles alternatives Open Source viennent aujourd'hui en proposant des alternatives sérieuses.

Je présenterais Infisical, une solution Open Source qui mise sur la simplicité d’utilisation, l’efficacité, et une compatibilité sans faille avec vos environnements de développement préférés.
Spoiler : gérer vos secrets n’a jamais été aussi simple, même avec des environnements multiples (prod/staging/dev/sandbox) – de quoi enfin donner à vos développeurs un sommeil un peu plus paisible.

Et ce n’est pas tout : depuis qu’Hashicorp (IBM) a pris un virage vers la BSL (Business Source License), certains challengers comme Infisical qui redouble d'arguments pour vous séduire.

Enfin, pour ne pas vous laisser sur votre faim, je conclurais avec une démonstration technique. Ainsi, vous découvrirez comment intégrer Infisical dans Kubernetes (grâce au Secret Operator dédié), mais aussi avec Ansible et plusieurs langages comme Java, Python et Go.

Je vous le promets, après cette conférence, gestion des secrets n'aura plus aucun secret pour vous !
```

==== Notes

Vault etait acheté par IBM.
OpenBAO est la version OSS de vault

Infisical est né en 2022. OSS
exist tne mode SaaS/enterprise ou OSS/self hosted.

les secret dans k8s sont pas vraiment des secret. c'est du base 64.
stocké dans la DB etcd, on peut les chopé dans les logs de l'api server.
Operator et CSI exists (comme pour vault)
CSI est pratique quand on veux pas passer par l'api server.

Infisical a aussi un agent qu'on peut deployer sur les pod de nos appli.

infisical a un scanner pour scanner les projet et etre sur qu'il y a pas de secret en claire

on dis chifré mais pas crypté.

== Vendredi

=== 9h00 - 9h25 (AMPHI BLEU) Plongé dans l'ere Quantic
==== Abstract
.speaker Fanny Bouton
Analyste, journaliste et experte en nouvelles technologies depuis plus de 20 ans, elle intervient régulièrement dans les médias et co-produit et anime les podcasts sur le quantique "Quantum" et "Decode Quantum" avec Olivier Ezratty.
Passionnée d'innovation, elle a lancé dès le début des années 2000 son blog et des soirées "Fanny's Party" dédiés au sujet. Pendant 18 ans, elle a réuni les geeks et vulgarisé les nouvelles technologies et innovations pour aider à la démocratisation des sujets complexes. Elle a animé bon nombre d'émissions comme "Quoi de neuf chez les geeks ?", "World of Fanny", "Follow Fanny", "Tech Away" et a été chroniqueuse pour Direct 8 ou encore GameOne.

```
La prochaine grande révolution industrielle après l’IA s’écrit déjà : l’informatique quantique. Longtemps considérée comme un concept lointain ou purement académique, cette technologie émergente est sur le point de bouleverser en profondeur l’univers du développement logiciel, des algorithmes et de l’architecture des systèmes.

Dans cette session, nous explorerons les notions clés qui rendent l’informatique quantique si puissante, en démystifiant des concepts essentiels tels que le qubit, l’intrication et la superposition. Nous verrons comment ces principes inédits ouvrent des perspectives vertigineuses pour la recherche, la cryptographie, l’optimisation ou encore la simulation.

L’objectif ? Vous donner un premier bagage de connaissances pratiques pour commencer à appréhender ce nouveau paradigme et aborder en toute confiance les outils, plateformes et langages de programmation quantique.

Ce talk s’adresse à tout développeur ou architecte passionné par l’innovation et curieux de comprendre comment la physique quantique est en passe de remodeler l’informatique.
```

==== Notes
il y a aujourdhuis une 10aine de different ordi quandtine.
il va faloir tjr des ordi normal pour piloter les ordi quandtic.
Par contre sur les ordi quandtic la facon de developer va etre completement different.
des atomes, des photons, des ion dans des diament, ect... chacun sa facon de developper du coup.
aujourdhuis ça va de 10 quibit a 150. ca fait pas grand chose.

on peut emuler des ordi quandtic sur les PC pour commencer à tester et
developper.



=== 9h35 - 10h00 (AMPHI BLEU) Les LLMs revent ils de cavaliers electriques ?
==== Abstract
.speaker Thibaut Giraud
Thibaut Giraud est docteur en philosophie et créateur de la chaîne de vulgarisation philosophique "Monsieur Phi" sur YouTube. Il porte un intérêt particulier aux LLM auxquels il consacré une dizaine de vidéo-essais et publiera cette année un livre sur le sujet.

```
Les LLM ne *comprennent*-ils rien parce qu'ils ne font que de la prédiction de prochain token ? *Comprendre* est un terme notoirement difficile à comprendre. Pour éclairer ce point, je voudrais discuter d'un usage des LLM très particulier : la génération de coups au jeu d'échecs. Un LLM pourrait-il jouer ne serait-ce qu'une partie entière sans coup illégal ? Des études ont mis en évidence que certains LLM sont capables de faire mieux que cela : ils jouent au niveau d'un bon joueur humain à partir seulement d'un historique de coups dont ils prédisent la suite. Plus intéressant encore : on peut montrer qu'ils se construisent spontanément un modèle interne du jeu. Cet exemple sur un cas précis est instructif pour réfléchir plus généralement à la question de savoir si les LLM ont un modèle du monde. Face à de tels résultats, il semble difficile de maintenir la position selon laquelle les LLM se réduisent à des "perroquets stochastiques".
```

==== Notes

=== 10h30 - 11h15 (NEUILLY 151) Si l’enfer existe, on y trouve des devs qui gérent des clés de chiffrement

.speaker Willy Malvault
Architecte sécurité chez Bpifrance depuis 2023, et dans l'IT depuis 2008. Conférencier sur les sujets Architecture, Cloud Native et sécurité. Je suis un adepte de la vulgarisation : un bon résumé, digeste, d'un sujet technique de 20, 40 ou 50 minutes, ça a une valeur inestimable pour moi, dans ce monde Tech où tout évolue si vite !
Organisateur du Snowcamp (Grenoble) et coach tremplins avec CraftsRecords.
Accessoirement improvisateur rookie.

==== Abstract
```
Dans un contexte géopolitique mondial instable et anxiogène, on nous demande de protéger nos données en chiffrant tout, partout et tout le temps… Alors on chiffe !

Et puis les exigences de sécurité arrivent : rotation de clé, chiffrement de clé, contrôle d’accès, audit d’utilisation des clés, stockage des clés sur une solution souveraine. C’est dur !
Pour couronner le tout, le PO a des idées lumineuses : on va faire de l’accès zero-knowledge ! Et puis de la tokenisation, ou encore du chiffrement homomorphique ! Et on arrive rapidement à devoir gérer des millions de clés pour des milliers d’utilisateurs.

Le temps où l'on pouvait passer une clé de chiffrement en paramètre de configuration d'un service (resp. d'une application) est alors révolu !

Deux alternatives s’offrent alors à nous :
Laisser des trous de sécurité béants dans nos applications en gérant nos clés comme on peut.
Automatiser la gestion de clés avec un KMS (Key Management Service) et avec le protocole KMIP, ou solution équivalente.

Si vous n’utilisez pas la deuxième alternative : venez vite voir ce talk ! Cela pourrait sauver vos données… et les quelques cheveux qu'ils vous reste !
```


DEK data encryption key
KEK key encryption key

BYOK(bring your own key) avec KMIP
on peut dire a GCP ou AWS de externaliser leur KMS chez nous avec KMIP.


==== Notes

=== 11h35 - 12h20 (Maillot) 45 min pour mettre son application à genoux : le guide complet du test de charge

.speaker Loïc Ortola
Quand Loïc n’est pas en train de militer pour qu’on ne copie-colle pas les réponses de StackOverflow sans regarder la doc, il intervient en architecture dans des contextes variés en tant que CTO de Takima. Il s’implique particulièrement à donner des visions d’ensemble concrètes pour que les développeurs puissent mieux dessiner leur système cible, et des retours d’expérience pour faire gagner du temps à ceux qui se lancent, parce que ça, on le trouve pas sur Stack Overflow.

.speaker Mathilde Lorrain
Mathilde a percé le secret de la fusion nucléaire et ne s’éteint jamais. On raconte même qu’EDF l’a contactée pour lui proposer un raccordement au réseau pour passer l’hiver.
Passionnée de DevOps et de Backend, elle aime quand les choses sont directes et efficaces. Comme elle. D’ailleurs, elle utilise volontiers son surplus d’énergie pour transmettre ses secrets. Il paraît même qu’elle va revenir faire une conf…

==== Abstract
```
45 minutes pour comprendre (un peu) comment ces algorithmes arrivent à écrire des poèmes ou répondre à des questions mieux que ta grand-mère.
Tout le monde n'a que ça à la bouche : "Generative AI". Parmi les modèles les plus captivants de cette sphère se trouvent les LLM et RAG (Retrieval-Augmented Generation). Ce talk technique vise à dévoiler les mécanismes et les principes fondamentaux qui animent ces puissantes architectures d’IA.
Plongée dans les Modèles de Langage à Grande Echelle (LLM)
```

===== Notes
.


=== 12h20 - 13h00 ------------------------------------- LUNCH -------------------------------------

=== 13h00 - 13h15 (Paris 141) Introduction à la cryptographie post-quantique
==== Abstract
.Speaker: Maxime Gosselin
Je travaille chez Oodrive depuis plus de 15 ans, d'abord en tant que développeur backend Java, puis comme architecte logiciel, et je suis aussi en charge des problématiques de sécurité au sein de nos applications.
Pendant cette période, Oodrive a notamment obtenu puis renouvelé sa qualification SecNumCloud auprès de l'ANSSI.

```
Les ordinateurs quantiques utilisables étant encore loin d'exister, pourquoi m'intéresser aujourd'hui à la cryptographie post-quantique ?
Je vous présenterai une réponse dans ce talk, du point de vue d'un éditeur SaaS de solutions de gestion de données sensibles.
Nous aborderons ensuite les recommandations pour la transition post quantique, émises par le NIST aux USA et l'ANSSI en France.
Pour finir, nous reviendrons à la technique avec un exemple de mise en place sur une application web.
```

=== 13h30 - 14h15 (Amphi bleu) Comment debugger en production ?
==== Abstract
.speaker Jean-Philippe Bempel
Développeur et Java Champion passionné par les performances, les runtimes (JVM, CLR) et adepte de Mechanical Sympathy, Jean-Philippe Bempel a plus de 8 ans d'expérience dans les systèmes de trading low latency. Après avoir optimisé les resources de larges clusters (2000+ noeuds) chez Criteo, Il a rejoint Datadog et développe un debugger de production.

```
Qui n'a jamais rêvé de rajouter une ligne de log à la volée sans redémarrer son application ? Ne pas avoir à attendre la fin de la CI puis du redéploiement des pods en prod ! Le cycle de vie des applications ayant beaucoup évolué ces dernières années, celui de l'investigation de problèmes (debugging/troubleshooting) n'a pas été facilité par ces évolutions.
Cette présentation va montrer comment nous avons construit un debugger de production qui est utilisé au quotidien pour résoudre des problèmes de prod et même plus !
Nous verrons que grâce à l'API d'instrumentation que nous fournit la JVM, il est possible de collecter toutes les données nécessaires pour une investigation tout en conservant un overhead faible compatible avec la production. Vous pourrez ainsi développer vos propres outils qui vous aideront à gérer vos incidents en toute sérénité !
```

===== Notes
pourquoi on voudrais debugger en prod ?
ajouter des log, spans, metrics.

JVM instrumentation API permet d'ajouter des feature a l'appli qui tourne.

on construit un agent, et ce agent va etre lancé avant le main de notre appli. Et ca va nous permetre d'instrumentatliser notre appli.

Instrumentation API  Nous permet de lancer un transformer quand la JVM charge une class.

image:

Y a des limite. Add/remove/rename fields or sig methods.
mais on peut changer le bytecode des method.

byteBuddy est tres pratique pour créer des java agent. Les tracer l'utilise beaucoup. Utilise ASM en dessous.

image:

ByteBuddy utilise les API (annotation) "Advice"

Faut faire gaff quand on capture plus de chose comme le context d'execution de ma method. Faut pas logger des truc sensible sans savoir.

faire du sampling pour eviter des boucle.
mettre des condition pour eviter trop de volume d'instrumentation.


example avoir l'argument de la method quand ca a peté une exception.
j'ai la stacktrace dans les logs sur Datadog, mais cetait quoi l'argument qui a causé ça ?


marche pas avec les native (graalVM ou GO) car il faut buildé l'agent avant. et donc ce n'est plus dynamic.
On fait ca avec les extension kernel ebee

=== 14h35 - 15h20 (Amphi bleu) Optimisation des requêtes PostgreSQL : Parlons Performance !
==== Abstract
.Speaker: Lætitia Avrot
Lætitia Avrot est une figure influente dans le monde de PostgreSQL. Elle est Trésorière de PostgreSQL Europe, fondatrice de Postgres Women et contributrice reconnue du projet PostgreSQL. Lætitia a découvert Postgres en 2007 et occupe actuellement le poste de Principal technical Product Marketing Manager chez EDB.

```
On a tous vu des requêtes lentes en production, et c'est difficile de prédire lesquelles vont exploser en premier. Certaines requêtes, cependant, peuvent vous mettre la puce à l'oreille quand vous faites votre premier EXPLAIN et vous faire dire qu'elles n'auraient jamais dû arriver en production.

À travers des exemples réels, je vous montrerai comment réécrire une requête peut transformer un job de 3 heures en un job de 3 minutes (et oui, tout le monde ne pense pas de manière holistique), comment EXPLAIN ANALYZE vous dit exactement ce qui ne va pas (fini les suppositions !), et comment les index peuvent aider ou plomber vos performances (oui, cet index que vous avez ajouté parce que Stack Overflow l'a dit).

Il semble aujourd'hui primordial de s'intéresser aux performances en base de données– parce que quel est l'intérêt de passer des heures à optimiser le code applicatif si votre requête fait un scan séquentiel ? Vous obtiendrez peut-être le graal avoir des requêtes stables quelle que soit la quantité de données requêtée. Aujourd'hui, nous levons le voile sur l'optimiseur de Postgres et vous verrez que ce n'est pas de la sorcellerie!
```

===== Notes

Optimiser des query ? ANALYZE
generalement on essaie de reduire le temps passé sur l'executor.

melanie pledgeman explique que fait le rewriter

l'ordre des join est important sur la performance.

les statistic nous permet d'avoir une idée de cout.
sur le scan d'un page en sequentiel, le cout d'un scan de page aleatoire ect...
ces cout vont etre important pour l'analyzer a prendre des decision.
On utilise un index ? ou on scan sequentiellement ?


optimizer fait des decision sur les donnée qu'il a :
1) les statistic
2) comment les donnée sont modelisé
violation du 2eme form normal

BRIN index est top pour les colonne deja ordonné (sparce index, c'est petit!)
Covering index (si il est dans index 1 pas la peine de chercher dans 2)
Partial index (avec un where)

index sur secondary key est utils car ça accelere les join.

quand on ajoute une index pour ameliorer une requete, penser à l'impacte sur les aux autres requetes !

check index usage regularly.

clustered table nous permet d'ordonner les row d'une table par rapport aux valeurs d'une colonne.

===  15h40 - 16h25 (Maillot) --- OPTIONNEL ---- The DDD Horror Picture Show
==== Abstract
.Speaker: Thomas PIERRAIN
VP of Engineering chez Agicap, Co-organisateur du meetup DDD FR , Speaker international (mais avec un accent de m...). Malgré une certaine passion pour le développement logiciel (écoles XP, Kanban & DDD) ainsi que pour le travail en équipe, Thomas ne désespère pas de trouver un autre moyen d’expression ou sa créativité sera -il l’espère- un peu plus reconnue.

```
La pratique du Domain-Driven Design (DDD) vous a-t-elle également amené à des situations déroutantes ? Dans ce talk, nous partagerons avec vous quelques-unes de nos petites histoires d’horreur pour vous aider à ne pas tomber dans les mêmes pièges. Par exemple, avez-vous déjà croisé la route d’un Bounded Context (BC) vampire qui absorbe compulsivement les modèles de données de ses congénères, les autres BCs ? Avez-vous déjà été pris d’obsession pour les agrégats ? Ou bien souffert d’envisager la cohérence à terme comme unique horizon ?

Le DDD est-il vraiment le coupable de certains de nos cauchemars, ou y a-t-il quelque chose de plus sombre qui se cache sous la surface ? En partant de quelques-unes de nos expériences angoissantes, nous allons vous faire reconsidérer ce que vous savez à propos du DDD, et révéler les véritables coupables derrière certains de nos tourments récurrents.

Une session aussi amusante qu’enrichissante dans laquelle nous vous dévoilerons quelques fantômes cachés du développement logiciel et certaines idées fausses qui peuvent hanter nos projets.
```

===== Notes


===  15h40 - 16h25 (Maillot) Au secours ! Mon manager me demande des KPIs !

.Speaker: Geoffrey graveaud
I have been working in the field of computer science for over 15 years.
I'm a specialist in Accelerate (the science behind DevOps ans Lean) and dora metrics and i am interested in all areas: DevSecOps, Security, Craft, Agility, Method, Product etc…
I gained extensive experience because I had the opportunity to work for thirty different organizations.
In my last experiences, I was CTO, Coach, Head of a consulting department, speaker, trainer, facilitator and event organizer.
I have been a speaker for 3 years (Voxxed Days, Devquest, DevOxx, DevFest, Agile Tour, MixIt, JugSummerCamp, Sunny Tech, BDX.io, etc.)
Currently, I am passionate about speaking coaching. In 1 year and half, I have already accompanied several 32 people especially for the preparation of TEDX, School of Product, for the contest of Miss Aquitaine, Opening Keynotes and for the springboards of speakers of Craft Records.
Currently, i'm coach DevOps / Accelerate & Craft at Inside (a provider of solutions, services, and added value for companies and IT departments aiming for agile digital transformation (Ops and Infrastructure • Support and management of IT projects • DevOps Transformation • Digital & Development)
You can find out more about my news https://insidegroup.fr/coachs-craft-accelerate-devops/[here]

==== Abstract
```
Kevin était un bon lead technique. Il travaillait dans une équipe de développement de 8 personnes. Il soutenait son équipe, il était respecté et il était écouté par son manager.

Mais un jour, son responsable lui demanda de mesurer la productivité de son équipe.
Et lui demanda la chose dont on ne dit pas le nom !
Des KPIs... 📈 😱
Ainsi, la vie de Kevin bascule et débute ainsi une période sombre.

Heureusement sur la route de son périple, il rencontre Eline - une coach agile expérimentée.
A eux 2, ils feront face à la cruauté du destin et ils chercheront à déjouer ce mauvais sort.
Rétabliront-ils la paix et l'ordre dans leur équipe ?

```

==== Note
Technique de sandwitch.
pain (du bon)
garniture (la merde)
encore du pain (du bon)

La performance collective ?
    l'integration continue
        test auto
        decoupage en petit lot
        feedback client
        management visuel
        monitoring/alerting

une pratique util ? ça impacte la performance

Avis de l'equipe ? créer un formulaire en respectant les regles de psycometrie.
Anonima et champs libre d'expression.
le resultat d'un formulaire doit etre indicative, pas neutre.
donc nombre de choix paire.
les question ne doit pas etre tendent à biaiser.

Effet ikea, on a construit un truc. il est pas ouf, mais on a finit de construire. on est content.

KPI utils ?
    intension
    attention
    emotion

keep people interested

=== 16h25 - 17h00 ------------------------------------- BREAK -----------------------------------

=== 17h00 - 17h30 (NEUILLY 153) Du full text search dans postgreSQL
==== Abstract
.Speakers: Zied Ben abderrahim
Développeur java depuis 2008, suis actuellement tech lead chez Capco où j'interviens dans la refonte des applications bancaires. Passionné, j'aime apprendre et partager sur tous les sujets qui touchent au développement et l architecture logicielle.

```
Aujourd'hui, quand on pense à mettre en place la recherche textuelle dans une application, les mots qui viennent spontanément sont : ElasticSearch, SoLR ou encore Lucene.

Qu’on se le dise : les solutions sont incroyables, et ont vraiment eu un gros impact dans de nombreux SIs. Mais en avez-vous vraiment besoin ?
Car déployer et maintenir des clusters ElasticSearch, gérer la manière dont on réplique la donnée à indexer, comment on la garde synchronisée...

Et s’il suffisait d’utiliser votre PostgreSQL, est-ce que ça ne serait pas beaucoup plus simple et moins cher ?

Nous commencerons par rappeler les concepts clé de recherche textuelle tels que le FTS, Stemming, IDF, rank et le Fuzzy search, puis nous irons mettre en place une intégration de Postgres search sur une application Spring Boot existante qui gère les transactions bancaires.

On terminera par une prise de hauteur sur ce qui marche bien, les limites du système, pour aider à prendre des décisions d’architecture dans vos projets.
```

===== Notes

=== 17h00 - 17h30 (Paris 143) Dagger Modules : un couteau suisse pour moderniser vos pipelines de CI/CD

.speaker: Jean-Christophe Sirot
Staff engineer chez Decathlon. Passionné de cryptographie, mais également intéressé par la CI/CD et le Cloud Native Computing. Je fais également parti de l'équipe du ParisJUG et j'ai co-créé le meetup Cloud Native Computing Paris. En 2024 je suis devenu Dagger Commander en contribuant à Dagger avec le SDK Java.

==== Abstract
```
Qui n'a jamais été démoralisé devant un pipeline de CI/CD bien complexe, impossible à maintenir, complexe à débuguer et dépendant de sa plateforme d'exécution ? En partant de ce constat que nous avons tous fait, Dagger renouvelle l'approche DevOps en permettant d'écrire des pipelines sous forme de code, exécutables localement, testables et portables sur n'importe quelle plateforme.

Dans cette session, je vous propose d'explorer les Dagger Functions et les Dagger Modules, qui permettent de créer et de partager des composants réutilisables et adaptables pour vos pipelines et ainsi de standardiser les workflows CI/CD. Et comme rien ne vaut un cas pratique, nous découvrirons comment transformer un workflow CI/CD existant en modules Dagger portables et maintenables tout en éliminant à la fois des kilomètres de fichiers YAML et le casse-tête de la dépendance aux plateformes spécifiques.

Cette présentation s'adresse aux développeurs et DevOps qui souhaitent moderniser leurs pratiques CI/CD tout en gardant le contrôle total sur leur code. Vous repartirez avec les clés pour transformer vos pipelines en composants modulaires, testables localement et utilisables partout.
```


=== Notes

Its great to build AI agents and CI/CD pipelines.
Tourne en locale. donc on peut le tester avant de push.
Portable sur tout les platform!

des fois on ajoute du bash ou python dans le yaml. plus besoin de script de CI complex comme ça.
Java peut etre utiliser pour coder le CI ! (version beta)

le module qu'on créer fait 2 choses:
il s'enregistre au pres de l'engine
implemente invoke() et decrit des parametres.
On peu les composer les module grace à ca.
