= Devoxx France 2024
:imagesdir: ./images 1️⃣
:toc: 2️⃣


== Mercredi
=== 09h00 - 09h25 (Amphi BLEU) bienvenu au devoxx 2024

.Speakers: Antonio, Nicolas Bartigole, Zouheir Cadi

Notes

=== 09h35 - 10h00 (Amphi BLEU) AI en medicine, ou somme nous
==== Abstract

.Speakers: Jean-Emmanuel Bibault

=== 10h00 - 10h30 -------------------------- BREAK -------------------------

=== 10h30 - 12h30 (Neuilly 152) refactorez votre code vers le data oriented programming
==== Abstract

.speaker José Paumard

=== 10h30 - 11h15 (Amphi BLEU) instrumentez votre appli spring boot et quarkus avec opentelemetry
==== Abstract

.speaker Bruno Baptista
.speaker Jean Bisutti

=== 11h15 - 11h35 -------------------------- BREAK -------------------------

=== 11h35 - 12h20 (Paris 141) High-Speed DDD (revisited)
==== Abstract
Faire du DDD quand tout va trop vite, c’est possible ? Le contexte de startup pousse très souvent les gens du produit à chercher en permanence à avoir de l’impact, et de l’impact à court terme. Mais si on se limite au court terme, on va très rapidement se retrouver incapable d’avancer. Tout simplement. A force de prendre des raccourcis, de contracter de la dette technique et encore pire: de la dette fonctionnelle… on se retrouve bloqué dans des ornières aux pires moments.
Alors comment survivre dans ce contexte et éviter la banqueroute liée à cette dette fonctionnelle qui ne fait que s’accumuler à cette cadence élevée ? Comment concilier cette urgence et la volonté de bien faire ? Comment garder une code base cohérente avec nos usages et notre domaine, tout en gardant une cadence acceptable pour le produit ?
Dans ce talk basé sur des cas réels et applicables dans des contextes hors start-up, nous verrons quelques solutions concrètes à ce problème mêlant DDD stratégique, architecture et design. Nous verrons aussi quelques patterns à la mode à absolument éviter en chemin et pourquoi… avant finalement de voir comment on peut tacler la cause originelle de cette tension Produit/Tech.

.speaker THOMAS PIERRAIN
VP of Engineering au sein d'une scale-up européenne en plein essor (Agicap), Thomas est un ancien entrepreneur, consultant, architecte et programmeur eXtreme obsédé par les cas d'usage (par opposition à l'approche orienté solution) depuis plus de 25 ans. Egalement co-organisateur des meetups DDD France (et ancien BDD Paris), Thomas aime utiliser l'autonomie, le DDD et le TDD pour booster son efficacité et celle des autres au travail.

=== 12h35 - 12h50 (Paris 242AB) SOPS, passez un savons a vos secret en clair
==== Abstract

.speaker Sylvain Meteyer

=== 13h00 - 13h30 ------------------------------------- LUNCH -----------------------------------

=== 13h30 - 14h15 (Paris 143) Bootiful spring boot 3.3
==== Abstract

.speaker Josh Long


=== 14h35 - 15h20 (Maillot) Nous somme ensemble, we are here together
==== Abstract

.speaker Remi Forax

=== 15h20 - 17h00 ------------------------------------- NETWORKING -----------------------------------


=== 17h00 - 17h30 (Paris 241) Zero thrust sur un cluster K8S avec Istio
==== Abstract

.speaker Anis Zouaoui

=== 17h30 - 17h50 ------------------------------------- BREAK -----------------------------------


=== 17h50 - 18h20 (Neuilly 252AB) La fin des mdp partagé avec Vault et Boundary
==== Abstract
On peut allier devX et sécurité. Fini les mots de passe de base de données partagés par toute l'équipe ! Fini les identifiants à durée de vie infinie !
Grâce à Boundary et Vault, il est possible, à partir de briques opensource, de mettre en place un système où chaque développeur est autorisé selon ses droits à accéder à des assets privés (serveur, base de donnée, cluster Kubernetes) sans posséder le moindre mot de passe.
Lors de cette démonstration technique, nous allons montrer l'implémentation des outils et des cas pratiques d'utilisation.

.speaker Clément Fage
Clément, SecOps @Padok, est passionné de cybersécurité et jongle entre execution d’attaques et plan de défenses des infrastructures cloud ! Il travaille également sur des sujets de recherches novateurs pour renforcer la sécurité du cloud. Présentateur amateur, il aime participer à des conférences pour partager ses connaissances et en apprendre plus avec celles des autres !

.speaker Josephine St-Joannis

== Jeudi

=== 09h00 - 09h25 (Amphi BLEU) Programming’s Greatest Mistakes
==== Abstract
.Speakers Mark Rendle
Mark is the founder of RendleLabs, which provides consulting services and workshops to .NET development teams across all industries. His particular obsessions are API design and development, performance, Observability and code-base modernisation. He also uses skills acquired during a few years as a professional stand-up comic to deliver entertaining and informative talks at conferences around the world, and recently learned to play bass so he could join tech parody band The LineBreakers.

```
Most of the time when we make mistakes in our code, a message gets displayed wrong or an invoice doesn’t get sent. But sometimes when people make mistakes in code, things literally explode, or bankrupt companies, or make web development a living hell for millions of programmers for years to come.
Join Mark on a tour through some of the worst mistakes in the history of programming. Learn what went wrong, why it went wrong, how much it cost, and how things can be pretty funny when they’re not happening to you.
```

Notes

=== 09h35 - 10h00 (Amphi BLEU) Un monde shooté aux métaux
==== Abstract
.Speakers GUILLAUME PITRON, AGNES CREPET
Éminent journaliste, auteur et réalisateur français basé à Paris, Guillaume Pitron est reconnu pour ses essais perspicaces sur les impacts cachés des transitions énergétique et numérique. Parmi ses œuvres notables figurent "La Guerre des métaux rares" et "L’Enfer numérique", tous deux traduits en plusieurs langues et salués par de nombreux prix. La carrière de Pitron s'étend à de nombreuses collaborations médiatiques et contributions à des publications majeures telles que Le Monde diplomatique et National Geographic, démontrant son expertise sur les défis économiques, géopolitiques et environnementaux posés par les avancées technologiques. Son journalisme d'investigation, couvrant plus d'une centaine de reportages dans de nombreux pays, explore des questions critiques comme l'extraction des terres rares et les implications de l'agriculture robotisée. L'engagement de Pitron auprès d'institutions internationales et de plateformes médiatiques, ainsi que ses affiliations académiques et reconnaissances, soulignent son rôle de voix clé dans les discussions sur la durabilité, la souveraineté technologique et l'avenir de notre planète.

Agnès Crepet est responsable de la longévité logicielle et de l'informatique chez Fairphone, une entreprise sociale créant un smartphone éthique, modulaire et réparable. Elle a cofondé Ninja Squad en France qui utilise et promeut l'Open Source et publie des livres informatiques à prix libre. Elle est également activement impliquée dans différentes communautés. Elle a cofondé MiXiT, un événement Tech annuel en France depuis 2011 qui travaille pour plus de diversité et d'éthique dans la Tech. Elle est également dans le board de Duchess France depuis 2010 qui rend les femmes dans l'informatique plus visibles.

https://ninja-squad.fr/
http://fairphone.com/
http://mixitconf.org/
https://www.duchess-france.org/

```
Dans cette conférence intitulée "Un monde shooté aux métaux", Guillaume Pitron, expert des enjeux géopolitiques liés aux ressources naturelles, et Agnes Crepet, spécialiste en technologies éco-responsables, s'unissent pour aborder la dépendance croissante de nos sociétés aux métaux rares et ses implications profondes. Ils exploreront comment cette consommation excessive impacte l'environnement, l'économie mondiale et les relations sociales, en dévoilant les chaînes d'approvisionnement complexes qui relient les mines isolées aux technologies quotidiennes. La discussion soulignera les conséquences environnementales de l'extraction des métaux, les défis éthiques et les tensions géopolitiques qu'elle engendre.
```

Notes

=== 10h00 - 10h30 -------------------------- BREAK -------------------------

=== 10h30 - 12h30 (Neuilly 152) Comprendre l'IA: construisez votre propre chatGPT avec LangChain4J
==== Abstract
.Speaker: YOHAN LASORSA
Open-source enthusiast and software craftsman, the web is the ultimate playground for Yohan. With a background of 15+ years in various fields such as applied research on mobile and IoT, architecture consulting and cloud applications development, he worked all the way down to the low-level stacks before diving into web development. As a full stack engineer and DIY hobbyist, he now enjoys pushing bits of JavaScript everywhere he can while sharing his passion with others.

.Speaker: JULIEN DUBOIS
Julien Dubois dirige deux équipes de Developer Advocates chez Microsoft, focalisées sur les technologies Java et JavaScript.
Il est connu pour être le créateur et principal développeur du projet JHipster, ainsi que pour être un Java Champion. Au cours des 20 dernières années, Julien a principalement travaillé sur les technologies Java et Spring, dirigeant des équipes techniques pour de nombreux clients à travers toutes les industries. Comme il aime partager sa passion, Julien a écrit un livre sur Spring, parlé à plus de 200 conférences internationales, et a créé plusieurs projets Open Source populaires.

```
Les technologies d'IA, et particulièrement les grand modèles de langages (LLM) poussent un peu partout comme des champignons ces derniers temps. Comment ces modèles fonctionnent-ils, et comment s'en servir dans vos applications?
Dans ce workshop, nous allons construire de zéro un chatbot basé sur GPT-4 implémentant le pattern Retrieval Augmented Generation (RAG). En utilisant une base de documents de référence, le modèle sera capable de répondre à des questions en langage naturel, et de générer des réponses complètes et sourcées dans vos documents. Pour cela, nous allons créer un service SpringBoot qui s'appuiera sur le framework open-source LangChain4J, ainsi qu'un site web pour tester notre chatbot. Enfin, nous déploierons le tout sur Azure.
```

Notes:

=== 12h35 - 12h50 (Paris 242AB) Je delegue tout mes tests à l'IA
==== Abstract
.Speaker: VALENTIN DUMAS
Craftsman chez Takima le jour, Développeur-Gourmand le soir, Valentin jongle avec les langages de programmation comme un chef cuisinier avec ses épices.
Expert enquêteur, s'il n'est pas au fourneau du logiciel, c'est qu'il est en train d'analyser la quantité de caféine consommée au Starbucks aux heures de pointe !
Détenteur d'un double diplôme Fullstack Java et d’explorateur Data, Valentin aime découvrir des pépites cachées.
Il saura vous guider pour dénicher de curieux trésors qui raviront vos papilles.
ainsi que pour être un Java Champion. Au cours des 20 dernières années, Julien a principalement travaillé sur les technologies Java et Spring, dirigeant des équipes techniques pour de nombreux clients à travers toutes les industries. Comme il aime partager sa passion, Julien a écrit un livre sur Spring, parlé à plus de 200 conférences internationales, et a créé plusieurs projets Open Source populaires.

```
Le craftsmanship et nos pratiques de développement moderne plébiscitent de tester efficacement nos applications. Et heureusement !
Pour autant, le test est rarement ce qu’on préfère réaliser au quotidien, et cela prend une partie non négligeable de notre temps.
D’ailleurs, on se dit même que le test, ce n’est pas vraiment la partie avec le meilleur ROI de l’utilisation de nos neurones.
Alors pourquoi pas faire faire nos tests à une IA ?
Dans cette conf, je vous présenterai Codium AI à travers des exemples concrets, et de son utilisation à la fois pour du Unit Testing que pour des tests plus complexes (e2e).
On prendra ensemble le temps de regarder ce qui marche bien, et aussi ses limites !
Une chose est sure : vous n’êtes pas prêts !
```

Notes:

=== 12h20 - 13h00 ------------------------------------- LUNCH -----------------------------------

=== 13h30 - 14h15 (Paris 143) La fin des archis event-based ? Orchestration avec Temporal
==== Abstract
.Speaker: HUGO CAUPERT
Sous ses faux airs de Steve Jobs, avec ses petites lunettes, son col roulé, et une calvitie pas trop assumée, Hugo était prédestiné à la tech. Fier papa de deux chatons et du tout dernier Macbook pro full options, il s’épanouit au quotidien sur des sujets de back, de front et de perf.
Hugo fait parti des gens qui scrollent des reels pendant des heures. Ne vous méprenez pas, il ne s’agit pas de la dernière chorée en vogue ou de jeux-vidéos, mais bien des dernières trends tech. Et bon, aussi parfois des chats…

```
Lorsqu’il s’agit d’architectures microservices, même en l’absence d’un consensus sur la bonne manière de faire, une réalité persiste : elles sont complexes. Actuellement, la plupart de ces architectures reposent sur un broker de message ou une plateforme de streaming, on parle alors de pattern choreography (event-based). Il est intéressant de noter qu’il existe une alternative moins connue, mais qui peut se montrer tout aussi efficace : le pattern orchestration. C’est précisément dans ce domaine que brille Temporal, une solution open-source sortie tout droit d’Uber.
Son leitmotiv : simplifier votre code, éliminant toute la plomberie superflue.
Rejoignez-moi dans 45 minutes de live coding d’un système de commande en ligne, simple mais puissant, efficace et fault-tolerant, tout ça en plain old java.
```

Notes:


=== 14h35 - 15h20 (Maillot) Password-less apps: implementing WebAuthN
==== Abstract
.Speaker: DANIEL GARNIER-MOIROUX
Daniel est ingénieur chez Broadcom, où il travaille sur des sujets de gestion d'identité et de SSO. Il enseigne également l'ingénierie informatique aux Mines de Paris.
Daniel contribue aux projets Spring Security. Il a un intérêt marqué pour l'automatisation et, plus généralement, la productivité dans l'ingénierie logicielle.

.Speaker: JOSH LONG
Josh (@starbuxman) has been the first Spring Developer Advocate since 2010. Josh is a Java Champion, author of 7 books (including "Reactive Spring") and numerous best-selling video training (including "Building Microservices with Spring Boot Livelessons" with Spring Boot co-founder Phil Webb), and an open-source contributor (Spring Boot, Spring Integration, Axon, Spring Cloud, Activiti, Vaadin, etc), a Youtuber (Coffee + Software with Josh Long as well as my Spring Tips series ), and a podcaster ("A Bootiful Podcast").

```
Passwords are everywhere, and they’re a mess! Once you create a good, strong, secure password, you’re rewarded with the task of having to rotate them periodically and store them! There’s got to be a better way. Spring Security is the world’s most widely used security framework for application developers, and it is here to help. In this talk, join us, Daniel Garnier-Moiroux (Spring Security contributor) and Josh Long (Developer Advocate Extraodinaire), as we look at WebAuthN - a protocol and framework for passwordless authentication based on physical devices, like a Yubikey, a macOS touchID, or iOS FaceID - and how to integrate it into a Spring Boot application.
```

Notes:

=== 15h40 - 16h25 (Neuilly 153) Et ANSI dit voila comment securiser un container
==== Abstract
.Speaker: YANN SCHEPENS
Originellement développeur PHP, je suis devenu avec le temps expert technique, Architecte, Évangéliste, Coach technique ; en résumé : Tech Lead.
Mes domaines de prédilection ?

```
De nos jours, une bonne partie de nos plateformes de développement et production fonctionnent avec Docker. Mais vous êtes déjà posé la question de la sécurisation de ce super outil ? Peut-être. En tout cas, l'ANSSI se l'est posé et à publier un certain nombre de recommandations relatives à la configuration et l'usage de Docker. Je vous propose de faire un tour ensemble de ce guide et vous découvrirez qu'il reste probablement quelques failles dans vos infras.
```

Notes:

=== 16h30 - 17h00 NETWORKING

=== 17h00 - 17h30 (Paris 241) Instrumentez vos applications Java avec OpenTelemetry !
==== Abstract
.Speaker: BRUCE BUJON
Bruce Bujon est ingénieur en Recherche & Développement chez Datadog. Il a passé près d'une quinzaine d'années à construire des systèmes distribués à l'aide du riche écosystème Java. Il mène aussi le Paris Java User Group et contribue à des projets Open Source liés à la vie privée tel son bloqueur de publicité AdAway. Quand il ne travaille pas, il est probablement en train de décompiler une application ou de souder son prochain prototype de gadget.

```
Second projet le plus actif de la CNCF derrière Kubernetes, OpenTelemetry s'est déjà imposé comme un standard incontournable de l'observabilité. Il permet d’instrumenter vos applications pour générer et exporter des traces, logs, et métriques de façon interopérable sans vendor lock-in.
Mais démarrer avec OpenTelemetry peut être intimidant avec beaucoup de concepts et de choix à faire lors de sa mise en œuvre. Quels sont les concepts clés à connaître ? Quelles sont les approches à explorer lorsque que l'on souhaite l'appliquer à son projet ? Comment poser les fondations de l'observabilité de son système distribué ?
Joignez-vous à Bruce Bujon pour une présentation pragmatique, illustrée par du live-coding, des différentes façons d'instrumenter vos applications Java via les outils offerts par OpenTelemetry. Il abordera et implémentera aussi bien les instrumentations manuelles via le SDK, que les supports natifs des différents frameworks, ou encore les instrumentations automatiques à base d'agent. Vous serez alors en mesure de générer des traces dans vos applications, de connaître les avantages et les inconvénients des différentes approches, de savoir comment propager un contexte dans un environnement distribué et bien plus encore. Ne ratez pas sa présentation et commencez à améliorer votre observabilité dès aujourd'hui !
```

Notes:

=== 17h00 - 17h30 (Paris 241) Builds Reproductibles avec Apache Maven
==== Abstract
.Speaker: Hervé Boutemy

```
Les Builds Reproductibles sont préconisés pour le niveau 4 de SLSA, pour atteindre le plus haut niveau de confiance sur un logiciel. Un tel niveau semble totalement inaccessible pour un projet normal.
En réalité, la plupart des distributions Linux ont implémenté les Builds Reproductibles ces 10 dernières années. Et depuis 5 ans, cela a été appliqué à de nombreux projets Open Source Java avec succès : plus de 2000 releases vérifiées reproductibles ont été publiées sur Maven Central par 500 projets, et ces chiffres ne cessent de croître.
Dans cette session, nous démistyfierons les pratiques pour les Builds Reproductibles telles qu'elles ont été éprouvées et améliorées sur le terrain. Nous expliquerons les outils utiles pour améliorer vos builds Maven et vérifier qu'ils sont réellement reproductibles : vous verrez, ce travail est riche d'enseignements utiles bien au delà de la sécurité.
Attention: si vous dormez pendant la session, vous aurez une sale note au quizz final permettant de vérifier les compétences acquises...
```

Notes:



== Vendredi

=== 9h00 - 9h25 (AMPHI BLEU) Comment modeliser l'etat du monde en 2100
==== Abstract
Comment modéliser l’état du monde en 2100 ? Pas la question la plus simple ! Mais en 1972 un groupe de chercheurs du MIT a essayé de répondre à cette question : c’est le fameux et fascinant rapport Meadows. Et ils ont compris bien des choses avant tout le monde. Dans cette conférence interactive, je vous fais un résumé en 20 minutes de la méthode et surtout des résultats du rapport Meadows !

.speaker ANATOLE CHOUARD
Je m’appelle Anatole, j’ai 27 ans et je suis vulgarisateur scientifique ! Pour ça j’ai 2 casquettes : je suis à la fois conférencier et sur YouTube. Après des études en classe préparatoire PC (Physique-Chimie), j’ai étudié les mathématiques appliquées à l’École Polytechnique, puis la modélisation mathématique à la University College de Londres. J’applique maintenant ces enseignements dans ma vulgarisation des sciences !

Notes

=== 9h35 - 9h55 (AMPHI BLEU) Cybercecurité, un sujet geopolitique
==== Abstract
La cybersécurité est souvent vue, à juste titre, sous un angle technique, opérationnel et réglementaire. L’incroyable évolution de la menace informatique nous concerne tous, à titre individuel, au niveau des organisations mais également à l’échelle des Etats. Dans un contexte général de fortes tensions géopolitiques, le cyber est devenu un ingrédient majeur dont l’usage se systématise dans des conflits qualifiés « d’hybrides ». Passionnante et effrayante, cette militarisation de l’espace numérique nous concerne toutes et tous !

.speaker GUILLAUME POUPARD
Polytechnicien (X92) et docteur en cryptographie, Guillaume Poupard débute sa carrière en tant que chef du laboratoire de cryptologie de la Direction Centrale de la Sécurité des Systèmes d’Information (DCSSI) qui deviendra, en 2009, l’Agence Nationale de la Sécurité des Systèmes d’Information (ANSSI).
En 2005, il rejoint le ministère de la Défense où il se spécialisera dans la cyberdéfense, avant d’intégrer en 2010 la Direction Générale de l’Armement (DGA) en tant que responsable des pôles sécurité des systèmes d’information et cyberdéfense. En 2014, il est appelé à prendre la direction générale de l’ANSSI, fonction qu’il occupera jusqu’à fin de l’année 2022.
En janvier 2023, il rejoint Docaposte en tant que Directeur Général Adjoint en charge notamment des domaines data/IA, cyber et cloud.

Notes


=== 10h30 - 12h30 (NEUILLY 253) Si j'etais un hacker, comment j'attaquerais votre K8S
==== Abstract
Un cluster Kubernetes est un orchestrateur de conteneurs qui permet de déployer et de gérer des applications de manière efficace. Cependant, en raison de sa complexité, un tel cluster peut facilement être vulnérable aux attaques et sa sécurité peut être compromise. Pour éviter cela, la meilleure option reste de tester ses défenses en se mettant dans la peau d’un attaquant !
Devenez vous-même un hacker pour la durée de cet atelier. Vous allez réaliser les différentes étapes de compromission un cluster Kubernetes et du compte AWS sous-jacent. Nous aborderons différentes techniques d’attaques en commençant par l'exécution de commandes sur un pod puis, grâce à différentes élévations de privilège, la compromission totale du cluster. Nous mettrons également en place des mesures préventives dans le but d’empêcher ces différentes failles de sécurité d’être exploitées.

.speaker THIBAULT LENGAGNE
Head of Cybersecurity à Padok, Thibault est en charge de la branche spécialisée en sécurité Cloud, en tant que directeur technique. Son but : allier Sécurité et DevOps pour trouver des solutions innovantes qui protègent les systèmes tout en améliorant le quotidien des développeurs.
Notes


=== 10h30 - 11h15 (NEUILLY 251) Model mithosys, ne pas se tromper entre monolith et microservices
==== Abstract
Tout comme le développement doit être itératif, le design du logiciel doit changer lorsque le contexte et notre compréhension du problème évoluent. Au fur et à mesure qu'un logiciel se développe pour résoudre plus de problèmes, il devient moins souple dans sa capacité à évoluer. Des tensions apparaissent au sein du modèle métier du logiciel qui peine à rester cohérent.
Finalement, il atteint une masse critique et devient un monolithe de code en spaghetti... Comment pouvons nous déterminer quand il est temps de modulariser notre logiciel ? Comment prendre la décision de le scinder en plusieurs modules ou services ? Comment gérer la différenciation progressive de nos modèles métiers tout en évitant les couplages inutiles ? Il n'est pas facile de découper son logiciel en deux car déterminer les bonnes frontières peut s'avérer être compliqué.
Découvrez avec nous le Model Mitosis, une approche dynamique utilisée pour diviser un modèle métier en plusieurs modèles qui seront façonnés et découplés de manière itérative. Gagnez en flexibilité afin de mieux déterminer quand diviser votre logiciel en plusieurs services tout en évitant de payer les coût d'échelle des microservices ou bien de devenir un monolithe distribué.

.speaker Julien TOPCU
Julien est un Tech Coach avec 15 ans d'expérience, spécialisé dans le Domain-Driven Design (#DDD). Son expertise réside dans l'aide aux organisations pour construire des systèmes à forte valeur métier. Julien se concentre sur l'alignement de l'organisation, de l'architecture et des pratiques logicielles avec le métier. En tant que membre de la fondation OWASP, il promeut activement les bonnes pratiques en matière de sécurité applicatives. Speaker international, Julien aime partager ses connaissances avec la communauté.
Fondateur de CraftsRecords, il aide les membres de notre communauté à se lancer dans le monde des conférences.

Notes


=== 11h35 - 12h15 (PARIS 242AB) Comment ça marche l'IA Generative ? LLM, RAG sous le capot.
==== Abstract
45 minutes pour comprendre (un peu) comment ces algorithmes arrivent à écrire des poèmes ou répondre à des questions mieux que ta grand-mère.
Tout le monde n'a que ça à la bouche : "Generative AI". Parmi les modèles les plus captivants de cette sphère se trouvent les LLM et RAG (Retrieval-Augmented Generation). Ce talk technique vise à dévoiler les mécanismes et les principes fondamentaux qui animent ces puissantes architectures d’IA.
Plongée dans les Modèles de Langage à Grande Echelle (LLM)

.speaker ARNAUD PICHERY
En tant que passionné par le développement logiciel, j'ai adoré avoir pu passer ces 30 dernières années à travailler dans ce domaine. En tant que VP Engineering chez Dataiku (la plateforme d'IA et d'apprentissage automatique leader dans le monde), je dirige actuellement les équipes qui travaillent sur le cœur de Dataiku DSS.
Développeur autodidacte, j'ai commencé à programmer en langage d'assemblage et en C, en développant des jeux. J'ai commencé ma carrière professionnelle en Californie, en travaillant sur la naissance de la plateforme Microsoft .NET.
De nos jours, si je ne suis pas en réunion d'équipe, en train de peaufiner un backlog, de passer en revue une nouvelle fonctionnalité ou de rédiger des spécifications, je tape certainement frénétiquement dans IntelliJ pour développer une nouvelle fonctionnalité DSS.
Notes


=== 11h35 - 12h15 (PARIS 143 Conference) Naviger dans le labyrinth de la gestion des dependences maven
==== Abstract
La gestion de dépendances est une partie cruciale mais complexe du développement d'applications modernes, souvent enveloppée de mystère et, avouons-le, parfois source d'angoisse ! Le périple commence dans le domaine de la JVM, où Gradle et Maven proposent des approches divergentes pour la résolution des dépendances, la gestion des conflits et les mécanismes de contrôle par l'utilisateur. Élargir le champ d'application à l'univers NPM révèle encore plus de contrastes.
Les différences clés émergent à partir de la gestion des dépôts centraux - comme Maven Central ou NPM registry - notamment en termes de confiance et de sécurité. Au sein d'un projet, le processus de résolution, les mécanismes de mise en cache et d'autres facteurs peuvent avoir un impact significatif sur la fiabilité et la reproductibilité des builds. Ces éléments influencent également ce qui apparaît dans les Software Bill Of Materials (SBOMs) et comment des outils comme GitHub fournissent des informations sur les graphes de dépendances pour les projets hébergés.
Cette session vise à doter les participants de connaissances approfondies sur ces paysages variés. Comprendre les subtilités, les choix et les limites des technologies utilisées est essentiel. Notre objectif est de vous fournir les connaissances et stratégies nécessaires pour éviter le redouté 'enfer des dépendances' dans votre prochain projet, assurant ainsi un processus de publication et de release fluide et sécurisé.

.speaker LOUIS JACOMET
Louis Jacomet has been perfecting his knowledge of Java for more than 20 years. Always a developer at heart, his role evolved over the last years to include technical team leading, coaching and some management. In addition to the bits and bytes, Louis is interested in people management skills mandatory to create a productive project team. To complete the buzzword bingo, Louis is interested in agile practices for the visibility, communication and result orientation it promotes. After working remotely from Belgium for Terracotta, with a focus on Ehcache, Louis is now part of the Gradle build tool team.

.speaker Hervé Boutemy


=== 12h20 - 13h00 ------------------------------------- LUNCH -----------------------------------

=== 13h00 - 13h15 (Paris 141) AssertJ comme un pro
==== Abstract

.speaker Thomas Fabre


=== 13h30 - 14h15 (MAIOLLOT Conference) Infra sans mdp, cauchemard des attaquant
==== Abstract

.speaker Thibault Langagne


=== 14h35 - 15h20 (MAILLOT Conference) programmer sa propre JVM avec JIT
==== Abstract

.speaker Olivier Poncet

=== 15h40 - 16h25 (Amphy BLEU Conference) progammation parallel SIMD avec l'API Vector
==== Abstract

.speaker José Paumard

=== 16h30 - 17h30 ------------------------------NETWORKING ------------------------------

=== 17h45 - 18h30 (NEUILLY 153) les cast codeurs en chair en os et en beret
==== Abstract

.speaker Antonio Goncalves, Arnaud Heritier, Katia Aresti
